# Generated by Django 5.2.10 on 2026-01-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20)),
            ],
            options={
                'ordering': ['price'],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='duration_days_positive'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_positive')],
            },
        ),
    ]
