# Generated by Django 5.2.10 on 2026-01-17 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('FROZEN', 'Frozen')], default='ACTIVE', max_length=10)),
                ('auto_renew', models.BooleanField(default=False)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frozen_from', models.DateField(blank=True, null=True)),
                ('frozen_to', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='plans.membershipplan')),
            ],
        ),
    ]
